highlights:
  - pattern: '(.*?)Persona\s*:'
    color: '#8d09c6'  # HEX color
    bold: true
  - pattern: '(.*?)Traits\s*:'
    color: '#08667f'  # HEX color
    bold: true
  - pattern: '(.*?)Kinks\s*:'
    color: '#cc16e1'  # HEX color
    bold: true
  - pattern: (.*?)\$Scenario\s*=\s*
    color: '#097809'  # HEX color
    bold: true
  - pattern: '\*(.+?)\*'  # *THIS*
    color: red
  - pattern: '\_(.+?)\_'  # *THIS*
    color: purple
  - pattern: '\"(.+?)\"'  # "THIS"
    color: blue
  - pattern: '(?s)```(.*?)```'  # ```THIS``` (matches across multiple lines)
    color: '#155909'  # Choose your desired color
    bold: true
  - pattern: '\*\*(.+?)\*\*'  # **THIS**
    color: green
    bold: true

text_background_from_yml:
    color: lightgray
txtbox_main_size:
    height: 8
    width: 150
txtbox_others_size:
    height: 5
    width: 150
